<?php
/**
 * GetImageInfoResult
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * GetImageInfoResult Class Doc Comment
 *
 * @category Class
 * @description Result of running a get-info operation on an image
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class GetImageInfoResult implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'GetImageInfoResult';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'successful' => 'bool',
        'color_space' => 'string',
        'color_type' => 'string',
        'width' => 'int',
        'height' => 'int',
        'compression_level' => 'int',
        'image_hash_signature' => 'string',
        'has_transparency' => 'bool',
        'mime_type' => 'string',
        'image_format' => 'string',
        'dpi_unit' => 'string',
        'dpi' => 'double',
        'color_count' => 'int',
        'bit_depth' => 'int',
        'comment' => 'string',
        'exif_profile_name' => 'string',
        'exif_values' => '\Swagger\Client\Model\ExifValue[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'successful' => null,
        'color_space' => null,
        'color_type' => null,
        'width' => 'int32',
        'height' => 'int32',
        'compression_level' => 'int32',
        'image_hash_signature' => null,
        'has_transparency' => null,
        'mime_type' => null,
        'image_format' => null,
        'dpi_unit' => null,
        'dpi' => 'double',
        'color_count' => 'int32',
        'bit_depth' => 'int32',
        'comment' => null,
        'exif_profile_name' => null,
        'exif_values' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'successful' => 'Successful',
        'color_space' => 'ColorSpace',
        'color_type' => 'ColorType',
        'width' => 'Width',
        'height' => 'Height',
        'compression_level' => 'CompressionLevel',
        'image_hash_signature' => 'ImageHashSignature',
        'has_transparency' => 'HasTransparency',
        'mime_type' => 'MimeType',
        'image_format' => 'ImageFormat',
        'dpi_unit' => 'DPIUnit',
        'dpi' => 'DPI',
        'color_count' => 'ColorCount',
        'bit_depth' => 'BitDepth',
        'comment' => 'Comment',
        'exif_profile_name' => 'ExifProfileName',
        'exif_values' => 'ExifValues'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'successful' => 'setSuccessful',
        'color_space' => 'setColorSpace',
        'color_type' => 'setColorType',
        'width' => 'setWidth',
        'height' => 'setHeight',
        'compression_level' => 'setCompressionLevel',
        'image_hash_signature' => 'setImageHashSignature',
        'has_transparency' => 'setHasTransparency',
        'mime_type' => 'setMimeType',
        'image_format' => 'setImageFormat',
        'dpi_unit' => 'setDpiUnit',
        'dpi' => 'setDpi',
        'color_count' => 'setColorCount',
        'bit_depth' => 'setBitDepth',
        'comment' => 'setComment',
        'exif_profile_name' => 'setExifProfileName',
        'exif_values' => 'setExifValues'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'successful' => 'getSuccessful',
        'color_space' => 'getColorSpace',
        'color_type' => 'getColorType',
        'width' => 'getWidth',
        'height' => 'getHeight',
        'compression_level' => 'getCompressionLevel',
        'image_hash_signature' => 'getImageHashSignature',
        'has_transparency' => 'getHasTransparency',
        'mime_type' => 'getMimeType',
        'image_format' => 'getImageFormat',
        'dpi_unit' => 'getDpiUnit',
        'dpi' => 'getDpi',
        'color_count' => 'getColorCount',
        'bit_depth' => 'getBitDepth',
        'comment' => 'getComment',
        'exif_profile_name' => 'getExifProfileName',
        'exif_values' => 'getExifValues'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['successful'] = isset($data['successful']) ? $data['successful'] : null;
        $this->container['color_space'] = isset($data['color_space']) ? $data['color_space'] : null;
        $this->container['color_type'] = isset($data['color_type']) ? $data['color_type'] : null;
        $this->container['width'] = isset($data['width']) ? $data['width'] : null;
        $this->container['height'] = isset($data['height']) ? $data['height'] : null;
        $this->container['compression_level'] = isset($data['compression_level']) ? $data['compression_level'] : null;
        $this->container['image_hash_signature'] = isset($data['image_hash_signature']) ? $data['image_hash_signature'] : null;
        $this->container['has_transparency'] = isset($data['has_transparency']) ? $data['has_transparency'] : null;
        $this->container['mime_type'] = isset($data['mime_type']) ? $data['mime_type'] : null;
        $this->container['image_format'] = isset($data['image_format']) ? $data['image_format'] : null;
        $this->container['dpi_unit'] = isset($data['dpi_unit']) ? $data['dpi_unit'] : null;
        $this->container['dpi'] = isset($data['dpi']) ? $data['dpi'] : null;
        $this->container['color_count'] = isset($data['color_count']) ? $data['color_count'] : null;
        $this->container['bit_depth'] = isset($data['bit_depth']) ? $data['bit_depth'] : null;
        $this->container['comment'] = isset($data['comment']) ? $data['comment'] : null;
        $this->container['exif_profile_name'] = isset($data['exif_profile_name']) ? $data['exif_profile_name'] : null;
        $this->container['exif_values'] = isset($data['exif_values']) ? $data['exif_values'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets successful
     *
     * @return bool
     */
    public function getSuccessful()
    {
        return $this->container['successful'];
    }

    /**
     * Sets successful
     *
     * @param bool $successful successful
     *
     * @return $this
     */
    public function setSuccessful($successful)
    {
        $this->container['successful'] = $successful;

        return $this;
    }

    /**
     * Gets color_space
     *
     * @return string
     */
    public function getColorSpace()
    {
        return $this->container['color_space'];
    }

    /**
     * Sets color_space
     *
     * @param string $color_space Color space of the image
     *
     * @return $this
     */
    public function setColorSpace($color_space)
    {
        $this->container['color_space'] = $color_space;

        return $this;
    }

    /**
     * Gets color_type
     *
     * @return string
     */
    public function getColorType()
    {
        return $this->container['color_type'];
    }

    /**
     * Sets color_type
     *
     * @param string $color_type Color type of the image
     *
     * @return $this
     */
    public function setColorType($color_type)
    {
        $this->container['color_type'] = $color_type;

        return $this;
    }

    /**
     * Gets width
     *
     * @return int
     */
    public function getWidth()
    {
        return $this->container['width'];
    }

    /**
     * Sets width
     *
     * @param int $width Width in pixels of the image
     *
     * @return $this
     */
    public function setWidth($width)
    {
        $this->container['width'] = $width;

        return $this;
    }

    /**
     * Gets height
     *
     * @return int
     */
    public function getHeight()
    {
        return $this->container['height'];
    }

    /**
     * Sets height
     *
     * @param int $height Height in pixels of the image
     *
     * @return $this
     */
    public function setHeight($height)
    {
        $this->container['height'] = $height;

        return $this;
    }

    /**
     * Gets compression_level
     *
     * @return int
     */
    public function getCompressionLevel()
    {
        return $this->container['compression_level'];
    }

    /**
     * Sets compression_level
     *
     * @param int $compression_level Compression level value from 0 (lowest quality) to 100 (highest quality)
     *
     * @return $this
     */
    public function setCompressionLevel($compression_level)
    {
        $this->container['compression_level'] = $compression_level;

        return $this;
    }

    /**
     * Gets image_hash_signature
     *
     * @return string
     */
    public function getImageHashSignature()
    {
        return $this->container['image_hash_signature'];
    }

    /**
     * Sets image_hash_signature
     *
     * @param string $image_hash_signature SHA256 hash signature of the image
     *
     * @return $this
     */
    public function setImageHashSignature($image_hash_signature)
    {
        $this->container['image_hash_signature'] = $image_hash_signature;

        return $this;
    }

    /**
     * Gets has_transparency
     *
     * @return bool
     */
    public function getHasTransparency()
    {
        return $this->container['has_transparency'];
    }

    /**
     * Sets has_transparency
     *
     * @param bool $has_transparency True if the image contains transparency, otherwise false
     *
     * @return $this
     */
    public function setHasTransparency($has_transparency)
    {
        $this->container['has_transparency'] = $has_transparency;

        return $this;
    }

    /**
     * Gets mime_type
     *
     * @return string
     */
    public function getMimeType()
    {
        return $this->container['mime_type'];
    }

    /**
     * Sets mime_type
     *
     * @param string $mime_type MIME type of the image format
     *
     * @return $this
     */
    public function setMimeType($mime_type)
    {
        $this->container['mime_type'] = $mime_type;

        return $this;
    }

    /**
     * Gets image_format
     *
     * @return string
     */
    public function getImageFormat()
    {
        return $this->container['image_format'];
    }

    /**
     * Sets image_format
     *
     * @param string $image_format Image format
     *
     * @return $this
     */
    public function setImageFormat($image_format)
    {
        $this->container['image_format'] = $image_format;

        return $this;
    }

    /**
     * Gets dpi_unit
     *
     * @return string
     */
    public function getDpiUnit()
    {
        return $this->container['dpi_unit'];
    }

    /**
     * Sets dpi_unit
     *
     * @param string $dpi_unit Units of the DPI measurement; can be either in Inches or Centimeters
     *
     * @return $this
     */
    public function setDpiUnit($dpi_unit)
    {
        $this->container['dpi_unit'] = $dpi_unit;

        return $this;
    }

    /**
     * Gets dpi
     *
     * @return double
     */
    public function getDpi()
    {
        return $this->container['dpi'];
    }

    /**
     * Sets dpi
     *
     * @param double $dpi DPI (pixels per unit, e.g. pixels per inch) of the image
     *
     * @return $this
     */
    public function setDpi($dpi)
    {
        $this->container['dpi'] = $dpi;

        return $this;
    }

    /**
     * Gets color_count
     *
     * @return int
     */
    public function getColorCount()
    {
        return $this->container['color_count'];
    }

    /**
     * Sets color_count
     *
     * @param int $color_count Unique colors in the image
     *
     * @return $this
     */
    public function setColorCount($color_count)
    {
        $this->container['color_count'] = $color_count;

        return $this;
    }

    /**
     * Gets bit_depth
     *
     * @return int
     */
    public function getBitDepth()
    {
        return $this->container['bit_depth'];
    }

    /**
     * Sets bit_depth
     *
     * @param int $bit_depth Bit depth of the image
     *
     * @return $this
     */
    public function setBitDepth($bit_depth)
    {
        $this->container['bit_depth'] = $bit_depth;

        return $this;
    }

    /**
     * Gets comment
     *
     * @return string
     */
    public function getComment()
    {
        return $this->container['comment'];
    }

    /**
     * Sets comment
     *
     * @param string $comment Comment string in the image
     *
     * @return $this
     */
    public function setComment($comment)
    {
        $this->container['comment'] = $comment;

        return $this;
    }

    /**
     * Gets exif_profile_name
     *
     * @return string
     */
    public function getExifProfileName()
    {
        return $this->container['exif_profile_name'];
    }

    /**
     * Sets exif_profile_name
     *
     * @param string $exif_profile_name Name of the EXIF profile used
     *
     * @return $this
     */
    public function setExifProfileName($exif_profile_name)
    {
        $this->container['exif_profile_name'] = $exif_profile_name;

        return $this;
    }

    /**
     * Gets exif_values
     *
     * @return \Swagger\Client\Model\ExifValue[]
     */
    public function getExifValues()
    {
        return $this->container['exif_values'];
    }

    /**
     * Sets exif_values
     *
     * @param \Swagger\Client\Model\ExifValue[] $exif_values EXIF tags and values embedded in the image
     *
     * @return $this
     */
    public function setExifValues($exif_values)
    {
        $this->container['exif_values'] = $exif_values;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


