<?php
/**
 * DocxMetadataCustomPropertyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * DocxMetadataCustomPropertyTest Class Doc Comment
 *
 * @category    Class
 * @description Name and value pair for a custom-defined DOCX metadata property
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DocxMetadataCustomPropertyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DocxMetadataCustomProperty"
     */
    public function testDocxMetadataCustomProperty()
    {
    }

    /**
     * Test attribute "property_name"
     */
    public function testPropertyPropertyName()
    {
    }

    /**
     * Test attribute "property_data_type"
     */
    public function testPropertyPropertyDataType()
    {
    }

    /**
     * Test attribute "string_value"
     */
    public function testPropertyStringValue()
    {
    }

    /**
     * Test attribute "integer_value"
     */
    public function testPropertyIntegerValue()
    {
    }

    /**
     * Test attribute "double_value"
     */
    public function testPropertyDoubleValue()
    {
    }

    /**
     * Test attribute "date_value"
     */
    public function testPropertyDateValue()
    {
    }
}
