<?php
/**
 * DocxStyleTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * DocxStyleTest Class Doc Comment
 *
 * @category    Class
 * @description Style in a DOCX Word Document
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DocxStyleTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DocxStyle"
     */
    public function testDocxStyle()
    {
    }

    /**
     * Test attribute "style_id"
     */
    public function testPropertyStyleId()
    {
    }

    /**
     * Test attribute "path"
     */
    public function testPropertyPath()
    {
    }

    /**
     * Test attribute "bold"
     */
    public function testPropertyBold()
    {
    }

    /**
     * Test attribute "italic"
     */
    public function testPropertyItalic()
    {
    }

    /**
     * Test attribute "underline"
     */
    public function testPropertyUnderline()
    {
    }

    /**
     * Test attribute "font_size"
     */
    public function testPropertyFontSize()
    {
    }

    /**
     * Test attribute "font_family"
     */
    public function testPropertyFontFamily()
    {
    }
}
