<?php
/**
 * FindRegexMatchTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * FindRegexMatchTest Class Doc Comment
 *
 * @category    Class
 * @description Individual regular expression match result of finding a target regex in a longer text string
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FindRegexMatchTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FindRegexMatch"
     */
    public function testFindRegexMatch()
    {
    }

    /**
     * Test attribute "character_offset_start"
     */
    public function testPropertyCharacterOffsetStart()
    {
    }

    /**
     * Test attribute "character_offset_end"
     */
    public function testPropertyCharacterOffsetEnd()
    {
    }

    /**
     * Test attribute "containing_line"
     */
    public function testPropertyContainingLine()
    {
    }

    /**
     * Test attribute "match_value"
     */
    public function testPropertyMatchValue()
    {
    }

    /**
     * Test attribute "match_groups"
     */
    public function testPropertyMatchGroups()
    {
    }
}
