<?php
/**
 * GetDocxGetCommentsHierarchicalRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * GetDocxGetCommentsHierarchicalRequestTest Class Doc Comment
 *
 * @category    Class */
// * @description Input to a Get Word DOCX Document comments hierarchically request
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetDocxGetCommentsHierarchicalRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "GetDocxGetCommentsHierarchicalRequest"
     */
    public function testGetDocxGetCommentsHierarchicalRequest()
    {
    }

    /**
     * Test attribute "input_file_bytes"
     */
    public function testPropertyInputFileBytes()
    {
    }

    /**
     * Test attribute "input_file_url"
     */
    public function testPropertyInputFileUrl()
    {
    }
}
