<?php
/**
 * GetImageInfoResultTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * GetImageInfoResultTest Class Doc Comment
 *
 * @category    Class */
// * @description Result of running a get-info operation on an image
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetImageInfoResultTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "GetImageInfoResult"
     */
    public function testGetImageInfoResult()
    {
    }

    /**
     * Test attribute "successful"
     */
    public function testPropertySuccessful()
    {
    }

    /**
     * Test attribute "color_space"
     */
    public function testPropertyColorSpace()
    {
    }

    /**
     * Test attribute "color_type"
     */
    public function testPropertyColorType()
    {
    }

    /**
     * Test attribute "width"
     */
    public function testPropertyWidth()
    {
    }

    /**
     * Test attribute "height"
     */
    public function testPropertyHeight()
    {
    }

    /**
     * Test attribute "compression_level"
     */
    public function testPropertyCompressionLevel()
    {
    }

    /**
     * Test attribute "image_hash_signature"
     */
    public function testPropertyImageHashSignature()
    {
    }

    /**
     * Test attribute "has_transparency"
     */
    public function testPropertyHasTransparency()
    {
    }

    /**
     * Test attribute "mime_type"
     */
    public function testPropertyMimeType()
    {
    }

    /**
     * Test attribute "image_format"
     */
    public function testPropertyImageFormat()
    {
    }

    /**
     * Test attribute "dpi_unit"
     */
    public function testPropertyDpiUnit()
    {
    }

    /**
     * Test attribute "dpi"
     */
    public function testPropertyDpi()
    {
    }

    /**
     * Test attribute "color_count"
     */
    public function testPropertyColorCount()
    {
    }

    /**
     * Test attribute "bit_depth"
     */
    public function testPropertyBitDepth()
    {
    }

    /**
     * Test attribute "comment"
     */
    public function testPropertyComment()
    {
    }

    /**
     * Test attribute "exif_profile_name"
     */
    public function testPropertyExifProfileName()
    {
    }

    /**
     * Test attribute "exif_values"
     */
    public function testPropertyExifValues()
    {
    }
}
