<?php
/**
 * ReplaceStringRegexRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ReplaceStringRegexRequestTest Class Doc Comment
 *
 * @category    Class
 * @description Request to replace a regex string in a string
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ReplaceStringRegexRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ReplaceStringRegexRequest"
     */
    public function testReplaceStringRegexRequest()
    {
    }

    /**
     * Test attribute "text_content"
     */
    public function testPropertyTextContent()
    {
    }

    /**
     * Test attribute "regular_expression_string"
     */
    public function testPropertyRegularExpressionString()
    {
    }

    /**
     * Test attribute "replace_with_string"
     */
    public function testPropertyReplaceWithString()
    {
    }
}
