<?php
/**
 * ConvertWebApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ConvertWebApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ConvertWebApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for convertWebHtmlToDocx
     *
     * Convert HTML to Word DOCX Document.
     *
     */
    public function testConvertWebHtmlToDocx()
    {
    }

    /**
     * Test case for convertWebHtmlToPdf
     *
     * Convert HTML string to PDF.
     *
     */
    public function testConvertWebHtmlToPdf()
    {
    }

    /**
     * Test case for convertWebHtmlToPng
     *
     * Convert HTML string to PNG screenshot.
     *
     */
    public function testConvertWebHtmlToPng()
    {
    }

    /**
     * Test case for convertWebHtmlToTxt
     *
     * Convert HTML string to text (txt).
     *
     */
    public function testConvertWebHtmlToTxt()
    {
    }

    /**
     * Test case for convertWebMdToHtml
     *
     * Convert Markdown to HTML.
     *
     */
    public function testConvertWebMdToHtml()
    {
    }

    /**
     * Test case for convertWebUrlToPdf
     *
     * Convert a URL to PDF.
     *
     */
    public function testConvertWebUrlToPdf()
    {
    }

    /**
     * Test case for convertWebUrlToScreenshot
     *
     * Take screenshot of URL.
     *
     */
    public function testConvertWebUrlToScreenshot()
    {
    }

    /**
     * Test case for convertWebUrlToTxt
     *
     * Convert website URL page to text (txt).
     *
     */
    public function testConvertWebUrlToTxt()
    {
    }
}
