<?php
/**
 * ConvertDataApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ConvertDataApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ConvertDataApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for convertDataCsvToJson
     *
     * Convert CSV to JSON conversion.
     *
     */
    public function testConvertDataCsvToJson()
    {
    }

    /**
     * Test case for convertDataCsvToXml
     *
     * Convert CSV to XML conversion.
     *
     */
    public function testConvertDataCsvToXml()
    {
    }

    /**
     * Test case for convertDataJsonStringToXml
     *
     * Convert JSON String to XML conversion.
     *
     */
    public function testConvertDataJsonStringToXml()
    {
    }

    /**
     * Test case for convertDataJsonToXml
     *
     * Convert JSON Object to XML conversion.
     *
     */
    public function testConvertDataJsonToXml()
    {
    }

    /**
     * Test case for convertDataXlsToJson
     *
     * Convert Excel (97-2003) XLS to JSON conversion.
     *
     */
    public function testConvertDataXlsToJson()
    {
    }

    /**
     * Test case for convertDataXlsxToJson
     *
     * Convert Excel XLSX to JSON conversion.
     *
     */
    public function testConvertDataXlsxToJson()
    {
    }

    /**
     * Test case for convertDataXlsxToXml
     *
     * Convert Excel XLSX to XML conversion.
     *
     */
    public function testConvertDataXlsxToXml()
    {
    }

    /**
     * Test case for convertDataXmlEditAddAttributeWithXPath
     *
     * Adds an attribute to all XML nodes matching XPath expression.
     *
     */
    public function testConvertDataXmlEditAddAttributeWithXPath()
    {
    }

    /**
     * Test case for convertDataXmlEditAddChildWithXPath
     *
     * Adds an XML node as a child to XML nodes matching XPath expression.
     *
     */
    public function testConvertDataXmlEditAddChildWithXPath()
    {
    }

    /**
     * Test case for convertDataXmlEditRemoveAllChildNodesWithXPath
     *
     * Removes, deletes all children of nodes matching XPath expression, but does not remove the nodes.
     *
     */
    public function testConvertDataXmlEditRemoveAllChildNodesWithXPath()
    {
    }

    /**
     * Test case for convertDataXmlEditReplaceWithXPath
     *
     * Replaces XML nodes matching XPath expression with new node.
     *
     */
    public function testConvertDataXmlEditReplaceWithXPath()
    {
    }

    /**
     * Test case for convertDataXmlEditSetValueWithXPath
     *
     * Sets the value contents of XML nodes matching XPath expression.
     *
     */
    public function testConvertDataXmlEditSetValueWithXPath()
    {
    }

    /**
     * Test case for convertDataXmlFilterWithXPath
     *
     * Filter, select XML nodes using XPath expression, get results.
     *
     */
    public function testConvertDataXmlFilterWithXPath()
    {
    }

    /**
     * Test case for convertDataXmlQueryWithXQuery
     *
     * Query an XML file using XQuery query, get results.
     *
     */
    public function testConvertDataXmlQueryWithXQuery()
    {
    }

    /**
     * Test case for convertDataXmlQueryWithXQueryMulti
     *
     * Query multiple XML files using XQuery query, get results.
     *
     */
    public function testConvertDataXmlQueryWithXQueryMulti()
    {
    }

    /**
     * Test case for convertDataXmlRemoveWithXPath
     *
     * Remove, delete XML nodes and items matching XPath expression.
     *
     */
    public function testConvertDataXmlRemoveWithXPath()
    {
    }

    /**
     * Test case for convertDataXmlToJson
     *
     * Convert XML to JSON conversion.
     *
     */
    public function testConvertDataXmlToJson()
    {
    }

    /**
     * Test case for convertDataXmlTransformWithXsltToXml
     *
     * Transform XML document file with XSLT into a new XML document.
     *
     */
    public function testConvertDataXmlTransformWithXsltToXml()
    {
    }
}
