<?php
/**
 * ConvertDocumentApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ConvertDocumentApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ConvertDocumentApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for convertDocumentAutodetectGetInfo
     *
     * Get document type information.
     *
     */
    public function testConvertDocumentAutodetectGetInfo()
    {
    }

    /**
     * Test case for convertDocumentAutodetectToPdf
     *
     * Convert Document to PDF.
     *
     */
    public function testConvertDocumentAutodetectToPdf()
    {
    }

    /**
     * Test case for convertDocumentAutodetectToPngArray
     *
     * Convert Document to PNG array.
     *
     */
    public function testConvertDocumentAutodetectToPngArray()
    {
    }

    /**
     * Test case for convertDocumentAutodetectToThumbnail
     *
     * Convert File to Thumbnail Image.
     *
     */
    public function testConvertDocumentAutodetectToThumbnail()
    {
    }

    /**
     * Test case for convertDocumentAutodetectToThumbnailsAdvanced
     *
     * Convert File to Thumbnail Image Object.
     *
     */
    public function testConvertDocumentAutodetectToThumbnailsAdvanced()
    {
    }

    /**
     * Test case for convertDocumentAutodetectToTxt
     *
     * Convert Document to Text (txt).
     *
     */
    public function testConvertDocumentAutodetectToTxt()
    {
    }

    /**
     * Test case for convertDocumentCsvToXlsx
     *
     * Convert CSV to Excel XLSX Spreadsheet.
     *
     */
    public function testConvertDocumentCsvToXlsx()
    {
    }

    /**
     * Test case for convertDocumentDocToDocx
     *
     * Convert Word DOC (97-03) Document to DOCX.
     *
     */
    public function testConvertDocumentDocToDocx()
    {
    }

    /**
     * Test case for convertDocumentDocToPdf
     *
     * Convert Word DOC (97-03) Document to PDF.
     *
     */
    public function testConvertDocumentDocToPdf()
    {
    }

    /**
     * Test case for convertDocumentDocToTxt
     *
     * Convert Word DOC (97-03) Document to Text (txt).
     *
     */
    public function testConvertDocumentDocToTxt()
    {
    }

    /**
     * Test case for convertDocumentDocxToPdf
     *
     * Convert Word DOCX Document to PDF.
     *
     */
    public function testConvertDocumentDocxToPdf()
    {
    }

    /**
     * Test case for convertDocumentDocxToPng
     *
     * Convert DOCX document to PNG image array.
     *
     */
    public function testConvertDocumentDocxToPng()
    {
    }

    /**
     * Test case for convertDocumentDocxToTxt
     *
     * Convert Word DOCX Document to Text (txt).
     *
     */
    public function testConvertDocumentDocxToTxt()
    {
    }

    /**
     * Test case for convertDocumentEmlToHtml
     *
     * Convert Email EML file to HTML string.
     *
     */
    public function testConvertDocumentEmlToHtml()
    {
    }

    /**
     * Test case for convertDocumentEmlToPdf
     *
     * Convert Email EML file to PDF document.
     *
     */
    public function testConvertDocumentEmlToPdf()
    {
    }

    /**
     * Test case for convertDocumentGetFileTypeIcon
     *
     * Get PNG icon file for the file extension.
     *
     */
    public function testConvertDocumentGetFileTypeIcon()
    {
    }

    /**
     * Test case for convertDocumentGetFileTypeIconAdvanced
     *
     * Get PNG icon byte array for the file extension.
     *
     */
    public function testConvertDocumentGetFileTypeIconAdvanced()
    {
    }

    /**
     * Test case for convertDocumentHtmlToPdf
     *
     * Convert HTML document file to PDF Document.
     *
     */
    public function testConvertDocumentHtmlToPdf()
    {
    }

    /**
     * Test case for convertDocumentHtmlToPng
     *
     * Convert HTML document file to PNG image array.
     *
     */
    public function testConvertDocumentHtmlToPng()
    {
    }

    /**
     * Test case for convertDocumentHtmlToTxt
     *
     * HTML Document file to Text (txt).
     *
     */
    public function testConvertDocumentHtmlToTxt()
    {
    }

    /**
     * Test case for convertDocumentMsgToHtml
     *
     * Convert Email MSG file to HTML string.
     *
     */
    public function testConvertDocumentMsgToHtml()
    {
    }

    /**
     * Test case for convertDocumentMsgToPdf
     *
     * Convert Email MSG file to PDF document.
     *
     */
    public function testConvertDocumentMsgToPdf()
    {
    }

    /**
     * Test case for convertDocumentPdfToDocx
     *
     * Convert PDF to Word DOCX Document.
     *
     */
    public function testConvertDocumentPdfToDocx()
    {
    }

    /**
     * Test case for convertDocumentPdfToDocxRasterize
     *
     * Convert PDF to Word DOCX Document based on rasterized version of the PDF.
     *
     */
    public function testConvertDocumentPdfToDocxRasterize()
    {
    }

    /**
     * Test case for convertDocumentPdfToPngArray
     *
     * Convert PDF to PNG Image Array.
     *
     */
    public function testConvertDocumentPdfToPngArray()
    {
    }

    /**
     * Test case for convertDocumentPdfToPngSingle
     *
     * Convert PDF to Single PNG image.
     *
     */
    public function testConvertDocumentPdfToPngSingle()
    {
    }

    /**
     * Test case for convertDocumentPdfToPptx
     *
     * Convert PDF to PowerPoint PPTX Presentation.
     *
     */
    public function testConvertDocumentPdfToPptx()
    {
    }

    /**
     * Test case for convertDocumentPdfToTxt
     *
     * Convert PDF Document to Text (txt).
     *
     */
    public function testConvertDocumentPdfToTxt()
    {
    }

    /**
     * Test case for convertDocumentPngArrayToPdf
     *
     * Convert PNG Array to PDF.
     *
     */
    public function testConvertDocumentPngArrayToPdf()
    {
    }

    /**
     * Test case for convertDocumentPptToPdf
     *
     * Convert PowerPoint PPT (97-03) Presentation to PDF.
     *
     */
    public function testConvertDocumentPptToPdf()
    {
    }

    /**
     * Test case for convertDocumentPptToPptx
     *
     * Convert PowerPoint PPT (97-03) Presentation to PPTX.
     *
     */
    public function testConvertDocumentPptToPptx()
    {
    }

    /**
     * Test case for convertDocumentPptxToPdf
     *
     * Convert PowerPoint PPTX Presentation to PDF.
     *
     */
    public function testConvertDocumentPptxToPdf()
    {
    }

    /**
     * Test case for convertDocumentPptxToPng
     *
     * Convert PowerPoint PPTX to PNG image array.
     *
     */
    public function testConvertDocumentPptxToPng()
    {
    }

    /**
     * Test case for convertDocumentPptxToTxt
     *
     * Convert PowerPoint PPTX Presentation to Text (txt).
     *
     */
    public function testConvertDocumentPptxToTxt()
    {
    }

    /**
     * Test case for convertDocumentXlsToCsv
     *
     * Convert Excel XLS (97-03) Spreadsheet to CSV.
     *
     */
    public function testConvertDocumentXlsToCsv()
    {
    }

    /**
     * Test case for convertDocumentXlsToPdf
     *
     * Convert Excel XLS (97-03) Spreadsheet to PDF.
     *
     */
    public function testConvertDocumentXlsToPdf()
    {
    }

    /**
     * Test case for convertDocumentXlsToXlsx
     *
     * Convert Excel XLS (97-03) Spreadsheet to XLSX.
     *
     */
    public function testConvertDocumentXlsToXlsx()
    {
    }

    /**
     * Test case for convertDocumentXlsxToCsv
     *
     * Convert Excel XLSX Spreadsheet to CSV, Single Worksheet.
     *
     */
    public function testConvertDocumentXlsxToCsv()
    {
    }

    /**
     * Test case for convertDocumentXlsxToCsvMulti
     *
     * Convert Excel XLSX Spreadsheet to CSV, Multiple Worksheets.
     *
     */
    public function testConvertDocumentXlsxToCsvMulti()
    {
    }

    /**
     * Test case for convertDocumentXlsxToPdf
     *
     * Convert Excel XLSX Spreadsheet to PDF.
     *
     */
    public function testConvertDocumentXlsxToPdf()
    {
    }

    /**
     * Test case for convertDocumentXlsxToPng
     *
     * Convert Excel XLSX spreadsheet to PNG image array.
     *
     */
    public function testConvertDocumentXlsxToPng()
    {
    }

    /**
     * Test case for convertDocumentXlsxToTxt
     *
     * Convert Excel XLSX Spreadsheet to Text (txt).
     *
     */
    public function testConvertDocumentXlsxToTxt()
    {
    }
}
