<?php
/**
 * ConvertDataApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ConvertDataApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ConvertDataApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for convertDataCsvToJson
     *
     * Convert CSV to JSON conversion.
     *
     */
    public function testConvertDataCsvToJson()
    {
    }

    /**
     * Test case for convertDataJsonToXml
     *
     * Convert JSON to XML conversion.
     *
     */
    public function testConvertDataJsonToXml()
    {
    }

    /**
     * Test case for convertDataXlsToJson
     *
     * Convert Excel (97-2003) XLS to JSON conversion.
     *
     */
    public function testConvertDataXlsToJson()
    {
    }

    /**
     * Test case for convertDataXlsxToJson
     *
     * Convert Excel XLSX to JSON conversion.
     *
     */
    public function testConvertDataXlsxToJson()
    {
    }

    /**
     * Test case for convertDataXmlToJson
     *
     * Convert XML to JSON conversion.
     *
     */
    public function testConvertDataXmlToJson()
    {
    }
}
