<?php
/**
 * EditPdfApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * EditPdfApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class EditPdfApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for editPdfAddAnnotations
     *
     * Add one or more PDF annotations, comments in the PDF document.
     *
     */
    public function testEditPdfAddAnnotations()
    {
    }

    /**
     * Test case for editPdfConvertToPdfA
     *
     * Convert a PDF file to PDF/A.
     *
     */
    public function testEditPdfConvertToPdfA()
    {
    }

    /**
     * Test case for editPdfDecrypt
     *
     * Decrypt and password-protect a PDF.
     *
     */
    public function testEditPdfDecrypt()
    {
    }

    /**
     * Test case for editPdfDeletePages
     *
     * Remove, delete pages from a PDF document.
     *
     */
    public function testEditPdfDeletePages()
    {
    }

    /**
     * Test case for editPdfDeletePagesBatchJob
     *
     * Remove, delete pages from a PDF document as Batch Job.
     *
     */
    public function testEditPdfDeletePagesBatchJob()
    {
    }

    /**
     * Test case for editPdfEncrypt
     *
     * Encrypt and password-protect a PDF.
     *
     */
    public function testEditPdfEncrypt()
    {
    }

    /**
     * Test case for editPdfGetAnnotations
     *
     * Get PDF annotations, including comments in the document.
     *
     */
    public function testEditPdfGetAnnotations()
    {
    }

    /**
     * Test case for editPdfGetAsyncJobStatus
     *
     * Get the status and result of a PDF Batch Job.
     *
     */
    public function testEditPdfGetAsyncJobStatus()
    {
    }

    /**
     * Test case for editPdfGetFormFields
     *
     * Gets PDF Form fields and values.
     *
     */
    public function testEditPdfGetFormFields()
    {
    }

    /**
     * Test case for editPdfGetMetadata
     *
     * Get PDF document metadata.
     *
     */
    public function testEditPdfGetMetadata()
    {
    }

    /**
     * Test case for editPdfGetPdfTextByPages
     *
     * Get text in a PDF document by page.
     *
     */
    public function testEditPdfGetPdfTextByPages()
    {
    }

    /**
     * Test case for editPdfInsertPages
     *
     * Insert, copy pages from one PDF document into another.
     *
     */
    public function testEditPdfInsertPages()
    {
    }

    /**
     * Test case for editPdfInsertPagesBatchJob
     *
     * Insert, copy pages from one PDF document into another as a batch job.
     *
     */
    public function testEditPdfInsertPagesBatchJob()
    {
    }

    /**
     * Test case for editPdfLinearize
     *
     * Linearize and optimize a PDF for streaming download.
     *
     */
    public function testEditPdfLinearize()
    {
    }

    /**
     * Test case for editPdfRasterize
     *
     * Rasterize a PDF to an image-based PDF.
     *
     */
    public function testEditPdfRasterize()
    {
    }

    /**
     * Test case for editPdfRasterizeBatchJob
     *
     * Rasterize a PDF to an image-based PDF as Batch Job.
     *
     */
    public function testEditPdfRasterizeBatchJob()
    {
    }

    /**
     * Test case for editPdfReduceFileSize
     *
     * Reduce the file size and optimize a PDF.
     *
     */
    public function testEditPdfReduceFileSize()
    {
    }

    /**
     * Test case for editPdfRemoveAllAnnotations
     *
     * Remove all PDF annotations, including comments in the document.
     *
     */
    public function testEditPdfRemoveAllAnnotations()
    {
    }

    /**
     * Test case for editPdfRemoveAnnotationItem
     *
     * Remove a specific PDF annotation, comment in the document.
     *
     */
    public function testEditPdfRemoveAnnotationItem()
    {
    }

    /**
     * Test case for editPdfResize
     *
     * Change PDF Document's Paper Size.
     *
     */
    public function testEditPdfResize()
    {
    }

    /**
     * Test case for editPdfRotateAllPages
     *
     * Rotate all pages in a PDF document.
     *
     */
    public function testEditPdfRotateAllPages()
    {
    }

    /**
     * Test case for editPdfRotatePageRange
     *
     * Rotate a range, subset of pages in a PDF document.
     *
     */
    public function testEditPdfRotatePageRange()
    {
    }

    /**
     * Test case for editPdfSetFormFields
     *
     * Sets ands fills PDF Form field values.
     *
     */
    public function testEditPdfSetFormFields()
    {
    }

    /**
     * Test case for editPdfSetMetadata
     *
     * Sets PDF document metadata.
     *
     */
    public function testEditPdfSetMetadata()
    {
    }

    /**
     * Test case for editPdfSetPermissions
     *
     * Encrypt, password-protect and set restricted permissions on a PDF.
     *
     */
    public function testEditPdfSetPermissions()
    {
    }

    /**
     * Test case for editPdfWatermarkText
     *
     * Add a text watermark to a PDF.
     *
     */
    public function testEditPdfWatermarkText()
    {
    }
}
