<?php
/**
 * EditHtmlApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * EditHtmlApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class EditHtmlApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for editHtmlHtmlAppendHeaderTag
     *
     * Append an HTML tag to the HEAD section of an HTML Document.
     *
     */
    public function testEditHtmlHtmlAppendHeaderTag()
    {
    }

    /**
     * Test case for editHtmlHtmlAppendHeading
     *
     * Append a Heading to an HTML Document.
     *
     */
    public function testEditHtmlHtmlAppendHeading()
    {
    }

    /**
     * Test case for editHtmlHtmlAppendImageFromUrl
     *
     * Append an Image to an HTML Document from a URL.
     *
     */
    public function testEditHtmlHtmlAppendImageFromUrl()
    {
    }

    /**
     * Test case for editHtmlHtmlAppendImageInline
     *
     * Append a Base64 Inline Image to an HTML Document.
     *
     */
    public function testEditHtmlHtmlAppendImageInline()
    {
    }

    /**
     * Test case for editHtmlHtmlAppendParagraph
     *
     * Append a Paragraph to an HTML Document.
     *
     */
    public function testEditHtmlHtmlAppendParagraph()
    {
    }

    /**
     * Test case for editHtmlHtmlCreateBlankDocument
     *
     * Create a Blank HTML Document.
     *
     */
    public function testEditHtmlHtmlCreateBlankDocument()
    {
    }

    /**
     * Test case for editHtmlHtmlGetLanguage
     *
     * Gets the language for the HTML document.
     *
     */
    public function testEditHtmlHtmlGetLanguage()
    {
    }

    /**
     * Test case for editHtmlHtmlGetLinks
     *
     * Extract resolved link URLs from HTML File.
     *
     */
    public function testEditHtmlHtmlGetLinks()
    {
    }

    /**
     * Test case for editHtmlHtmlGetRelCanonical
     *
     * Gets the rel canonical URL for the HTML document.
     *
     */
    public function testEditHtmlHtmlGetRelCanonical()
    {
    }

    /**
     * Test case for editHtmlHtmlGetSitemap
     *
     * Gets the sitemap URL for the HTML document.
     *
     */
    public function testEditHtmlHtmlGetSitemap()
    {
    }

    /**
     * Test case for editHtmlHtmlSetLanguage
     *
     * Sets the language for the HTML document.
     *
     */
    public function testEditHtmlHtmlSetLanguage()
    {
    }

    /**
     * Test case for editHtmlHtmlSetRelCanonical
     *
     * Sets the rel canonical URL for the HTML document.
     *
     */
    public function testEditHtmlHtmlSetRelCanonical()
    {
    }

    /**
     * Test case for editHtmlHtmlSetSitemapUrl
     *
     * Sets the sitemap URL for the HTML document.
     *
     */
    public function testEditHtmlHtmlSetSitemapUrl()
    {
    }
}
