<?php
/**
 * SplitDocumentApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * SplitDocumentApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SplitDocumentApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for splitDocumentBatchJobCreate
     *
     * Split a single Document into Separate Documents by Page as a Batch Job.
     *
     */
    public function testSplitDocumentBatchJobCreate()
    {
    }

    /**
     * Test case for splitDocumentDocx
     *
     * Split a single Word Document DOCX into Separate Documents by Page.
     *
     */
    public function testSplitDocumentDocx()
    {
    }

    /**
     * Test case for splitDocumentGetAsyncJobStatus
     *
     * Get the status and result of a Split Document Batch Job.
     *
     */
    public function testSplitDocumentGetAsyncJobStatus()
    {
    }

    /**
     * Test case for splitDocumentPdfByPage
     *
     * Split a PDF file into separate PDF files, one per page.
     *
     */
    public function testSplitDocumentPdfByPage()
    {
    }

    /**
     * Test case for splitDocumentPptx
     *
     * Split a single PowerPoint Presentation PPTX into Separate Slides.
     *
     */
    public function testSplitDocumentPptx()
    {
    }

    /**
     * Test case for splitDocumentPptxAdvanced
     *
     * Split a single PowerPoint Presentation PPTX into Separate Presentations.
     *
     */
    public function testSplitDocumentPptxAdvanced()
    {
    }

    /**
     * Test case for splitDocumentTxtByLine
     *
     * Split a single Text file (txt) into lines.
     *
     */
    public function testSplitDocumentTxtByLine()
    {
    }

    /**
     * Test case for splitDocumentTxtByString
     *
     * Split a single Text file (txt) by a string delimiter.
     *
     */
    public function testSplitDocumentTxtByString()
    {
    }

    /**
     * Test case for splitDocumentXlsx
     *
     * Split a single Excel XLSX into Separate Worksheets.
     *
     */
    public function testSplitDocumentXlsx()
    {
    }
}
