<?php
/**
 * TransformDocumentApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * TransformDocumentApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TransformDocumentApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for transformDocumentDocxReplace
     *
     * Replace string in Word DOCX document, return result.
     *
     */
    public function testTransformDocumentDocxReplace()
    {
    }

    /**
     * Test case for transformDocumentDocxReplaceEditSession
     *
     * Replace string in Word DOCX document, return edit session.
     *
     */
    public function testTransformDocumentDocxReplaceEditSession()
    {
    }

    /**
     * Test case for transformDocumentDocxTableFillIn
     *
     * Fill in data in a table in a Word DOCX document, return result.
     *
     */
    public function testTransformDocumentDocxTableFillIn()
    {
    }

    /**
     * Test case for transformDocumentDocxTableFillInEditSession
     *
     * Fill in data in a table in a Word DOCX document, return edit session.
     *
     */
    public function testTransformDocumentDocxTableFillInEditSession()
    {
    }

    /**
     * Test case for transformDocumentDocxTableFillInMulti
     *
     * Fill in data in multiple tables in a Word DOCX document, return result.
     *
     */
    public function testTransformDocumentDocxTableFillInMulti()
    {
    }

    /**
     * Test case for transformDocumentPptxReplace
     *
     * Replace string in PowerPoint PPTX presentation, return result.
     *
     */
    public function testTransformDocumentPptxReplace()
    {
    }
}
